Update lite-software

diff --git a/32/usr/bin/lite-software b/32/usr/bin/lite-software
--- a/32/usr/bin/lite-software
+++ b/32/usr/bin/lite-software
@@ -1,8 +1,7 @@
 #! /bin/bash
 #--------------------------------------------------------------------------------------------------------
 # Name: Linux Lite Additional Software Install
-# Description: A GUI tool to easily install and remove additional software in Linux Lite.
-# Authors: Misko_2083, Jerry Bezencon, gerito1, Johnathan "ShaggyTwoDope" Jenkins
+# Authors: Misko_2083, Jerry Bezencon, gerito1, Johnathan "ShaggyTwoDope" Jenkins, Ralphy
 # Website: https://www.linuxliteos.com
 #--------------------------------------------------------------------------------------------------------
 
@@ -31,22 +30,30 @@ log(){
 # Log last activities to retrieve errors
 TMP_LOG=/tmp/lite-software.log
 
-# Check if apt-cache was built and ask for update if needed
 prepare(){
-  if zenity --question --title="Update Sources" --window-icon=$ic --text="We will now update your software sources.\n\nClick Yes to continue or No to abort."; then
-    TOTALREPOS=$(cat /etc/apt/sources.list | grep '^deb' -c) # Total of repositories registered, this is approximated
-    sudo apt-get update 2>&1 | awk -v total=$TOTALREPOS '/^Ign|^ Get/{count++;$1=""} FNR { if (total != 0){percentage=int (100*count/total);print (percentage < 90?percentage:90),"\n#",$0 }; fflush(stdout)}' \
-      | zenity --progress --text="Updating package lists..." --window-icon=$ic --title="Updating Software Sources - please wait..." --percentage=0 --auto-close --width=600
-    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-      zenity --error --title="Error" --text="Updating sources has failed.\n\nRefer to /var/log/lite-software.log\n\nfor more information."
-      log "ERROR: Updating sources has failed."
-      exit 0
-    fi
-    log "INFO: Software sources were updated."
-  else
-    log "INFO: The updating of packages was cancelled by the user"
-    exit
-  fi
+	# Check internet access
+	if eval "sudo -u ${SUDO_USER:-$USER} curl -sk https://www.linuxliteos.com/" >> /dev/null 2>&1; then
+	: # pass
+	else # Prompt ERROR internet connection
+		(zenity --info --ok-label="Got it!" --title="No Internet connection detected..." \
+			     --text="\n<b>Your computer does not seem to be connected to the internet</b> \n \nYou won't be able to install applications packages needed to be downloaded from the Internet." --no-wrap)
+		return 
+	fi
+   # Check if apt-cache was built and ask to update    	    	
+ 	if zenity --question --width=400 --height=120 --title="     Update software sources" --window-icon=$ic --text="\n<b>Would you like to update your software sources now?</b>\n\nClick 'No' to continue without updating software sources or 'Yes' to update software sources next. \n \nIt is recommended to always update software sources before installing applications."; then
+		TOTALREPOS=$(cat /etc/apt/sources.list | grep '^deb' -c) # Total of repositories registered, this is approximated
+    		sudo apt-get update 2>&1 | awk -v total=$TOTALREPOS '/^Ign|^ Get/{count++;$1=""} FNR { if (total != 0){percentage=int (100*count/total);print (percentage < 90?percentage:90),"\n#",$0 }; fflush(stdout)}' \
+       		| zenity --progress --text="Updating package lists..." --window-icon=$ic --title="Updating Software Sources - please wait..." --percentage=0 --auto-close --width=600
+    		if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+      			zenity --error --title="          Error" --width=300 --height=90 --text="\n<b>Updating sources has failed</b>\n\nRefer to /var/log/lite-software.log for more information."
+      			log "ERROR: Updating sources has failed."
+      			next
+    		fi
+    		log "INFO: Software sources were updated."
+  	else
+    		log "INFO: The updating of packages was cancelled by the user"
+    	next
+  	fi
 }
 
 # Set app icon variable
@@ -109,7 +116,7 @@ extras=("$APPICON/extras.png" "Restricted Extras" "Multimedia" "" "Additional co
 skype=("$APPICON/skype.png" "Skype" "Internet" "" "A popular audio and video chat application" "skype-bin" "skype" )
 spotify=("$APPICON/spotify.png" "Spotify" "Multimedia" "" "Spotify is a digital music service" "spotify-client" "" )
 steam=("$APPICON/steam.png" "Steam" "Games" "" "Steam is a cross platform gaming client" "steam-launcher" "" )
-teamviewer=("$APPICON/teamviewer.png" "Teamviewer" "Internet" "" "Teamviewer Remote Desktop Support software" "teamviewer" "" )
+teamviewer=("$APPICON/teamviewer.png" "Teamviewer" "Internet" "" "Teamviewer Remote Desktop Support software" "teamviewer:i386" "" )
 torrent=("$APPICON/deluge.png" "Torrent Software" "Internet" "" "Deluge Torrent client software" "deluge deluge-common" "" )
 tor=("$APPICON/tor.png" "Tor Web Browser" "Internet" "" "Tor Web Browser a privacy respecting web browser" "tor-web-browser" "" )
 videoedit=("$APPICON/openshot.png" "Video Editing Software" "Multimedia" "" "Openshot, a simple to use yet powerful video editor for linux" "openshot blender imagemagick" "")
@@ -149,14 +156,14 @@ install_pkgs(){
 
   log "INFO: Installation of packages initiated: ${pkg_arr[@]}"
   sudo apt-get install -f --show-progress ${pkg_arr[@]} --force-yes -y 2>&1 | tee $TMP_LOG | awk ' BEGIN { FS=" "; total=1;end_download=0} /upgraded/ {total= $1 + $3;FS="[ :]" } /^Get:[[:digit:]]+/ {printf "#Downloading %s %s %s\n",$7,$(NF-1),$NF;print int(($2 - 1) * 100 / total); fflush(stdout)} /^\(Reading / {if (end_download==0){print 100;fflush(stdout);end_download=1}} /^(Preparing|Unpacking|Selecting|Processing|Setting|Download)/ {print "#", $0; fflush(stdout)}  /^Progress/ {print  match($0, /([0-9]+)/, arr); if(arr[1] != "") print arr[1] ; fflush(stdout)}' \
-    | ( zenity --window-icon=$ic --progress --width=600 --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage=0 --auto-close ; zenity --progress --window-icon=$ic --width=600 --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..." --auto-close )
+   | ( zenity --window-icon=$ic --progress --width=600 --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage=0 --auto-close ; zenity --progress --window-icon=$ic --width=600 --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..." --auto-close )
   if [ "${PIPESTATUS[0]}" -ne "0" ]; then
     err_msg=$(awk '/^E:/{$1=""; print $0}' $TMP_LOG | tail -n 1)
     log "ERROR:$err_msg"
     zenity --error --title="Error" --text="Error\n$err_msg"
     return
   else
-    zenity --info --title="Install Complete" --text="The package(s) installed successfully."
+    zenity --info --width=240 --height=80 --title="          Installation Info" --text="\nInstallation successfully completed!"
     log "INFO: Installation was a success."
   fi
 }
@@ -173,7 +180,7 @@ remove_pkgs(){
     zenity --error --title="Error" --text="Error\n$err_msg"
     return
   else
-    zenity --info --title="Removal Complete" --text="The package(s) uninstalled successfully."
+    zenity --info --width=240 --height=80 --title="          Removal Info" --text="\nRemoval successfully completed!"
     log "INFO: Removal was a success."
   fi
 }
@@ -187,18 +194,18 @@ install_menu(){
       row=$element[@]                          #grab the whole row
       printf  '%s\n' "${!row}"                 #print every element in the row separated with a newline
     done | zenity --window-icon="$ic" --list --imagelist --multiple --width=920 --height=760 --print-column=2,6,7 --separator="| " --column="Select" --column="Name" --column="Category" --column="Status" \
-      --column="Description" --column="Packages" --column="Optional Packages" --text="Select the program you wish to install, then click the Install button. Sort Categories by clicking on the column.\nYou can select multiple programs to install by holding down the Ctrl or Shift keys." \
+      --column="Description" --column="Packages" --column="Optional Packages" --text="Select the program you wish to install, then click the Install button. \n- Sort columns by clicking on column headers. \n- Ctrl key - allows you to click and select multiple applications that are <b>anywhere</b> on the list, not necessarily next to each other. \n- Shift key - allows you to select a group of applications that are <b>contiguous</b> (next to each other) by clicking one application, then holding Shift \n  and clicking the last application you want from the list; all the applications in between will be selected.\n " \
       --title="Install Additional Software" --ok-label="Install" --hide-column=6,7 )
 
   # If Cancel is clicked then return to main loop
   if [ "${PIPESTATUS[0]}" -ne "0" ]; then
     return
   fi
-
+  
   # Check if anything is selected
   echo $selection | grep '[a-zA-Z0-9]'
   if [ "${PIPESTATUS[1]}" -ne "0" ]; then
-    zenity --info --title='Install Additional Software' --text='Nothing was selected for installation.'
+    zenity --info  --width=280 --title='     Install Additional Software' --text='\nNo application was selected for installation.'
     return
   fi
 
@@ -218,7 +225,7 @@ install_menu(){
   done
   IFS=$OIFS
 
-  zenity --question --title="Install Software" --window-icon="${ic}" --text="The following software is selected for installation:\n\n $PKGS_NAMES \n Do you want to proceed?"
+  zenity --question  --width=360 --title="          Install Software" --window-icon="${ic}" --text="\n<b>The following software has been selected</b>:\n\n $PKGS_NAMES \nDo you want to proceed with the installation?"
   if [ "$?" -eq "0" ]; then
     install_pkgs PKGS[@]
   else
@@ -243,7 +250,7 @@ remove_menu(){
       row=$element[@]                          #grab the whole row
       printf  '%s\n' "${!row}"                 #print every element in the row separated with a newline
     done | zenity --window-icon="$ic" --list --imagelist --multiple --width=920 --height=760 --print-column=2,6 --separator="| " --column="Select" --column="Name" --column="Category" --column="Status" \
-      --column="Description" --column="Packages" --column="Optional Packages" --text="Select the program you wish to remove, then click the Remove button. Sort Categories by clicking on the column.\nYou can select multiple programs to remove by holding down the Ctrl or Shift keys." \
+      --column="Description" --column="Packages" --column="Optional Packages" --text="Select the program you wish to remove, then click the Remove button. \n- Sort columns by clicking on column headers. \n- Ctrl key - allows you to click and select multiple applications that are <b>anywhere</b> on the list, not necessarily next to each other. \n- Shift key - allows you to select a group of applications that are <b>contiguous</b> (next to each other) by clicking one application, then holding Shift \n  and clicking the last application you want from the list; all the applications in between will be selected." \
       --title="Remove Additional Software" --ok-label="Remove" --hide-column=6,7 )
 
   # If Cancel is clicked then return to main loop
@@ -254,7 +261,7 @@ remove_menu(){
   # Check if anything is selected
   echo $selection | grep '[a-zA-Z0-9]'
   if [ "${PIPESTATUS[1]}" -ne "0" ]; then
-    zenity --info --title='Remove Software' --text='Nothing was selected for removal.'
+    zenity --info --width=260 --title='          Remove Software' --text='\nNo application was selected for removal.'
     return
   fi
 
@@ -273,7 +280,7 @@ remove_menu(){
     PKGS=$PKGS${selection_array[$i]}" "
   done
   IFS=$OIFS
-  zenity --question --title="Remove Software" --window-icon="${ic}" --text="The following software is selected for removal:\n\n $PKGS_NAMES \n Do you want to proceed?"
+  zenity --question --width=360 --title="          Remove Software" --window-icon="${ic}" --text="\n<b>The following software has been selected</b>:\n\n $PKGS_NAMES \n Do you want to proceed  with the removal?"
   if [ "$?" -eq "0" ]; then
     remove_pkgs PKGS[@]
   else
@@ -286,9 +293,9 @@ prepare
 pkg_manager_check
 # The main loop
 while (true); do
-  TASK=$(zenity --width=250 --height=180 --list --radiolist --text="Select a task:" \
-    --title="Lite Software" --column="Select" --column="Task" --column="Code Task" --hide-column=3 \
-    --print-column=3 --cancel-label="Quit" TRUE "Install Software" 1 FALSE "Remove Software" 2 FALSE "Exit" 3)
+  TASK=$(zenity --width=280 --height=160 --list --radiolist --text="Select a task:" \
+    --title="          Lite Software" --column="Select" --column="Task" --column="Code Task" --hide-column=3 \
+    --print-column=3 --cancel-label="Quit" TRUE "Install Software" 1 FALSE "Remove Software" 2)
   if [ "${PIPESTATUS[0]}" -ne "0" ]; then
     exit 0
   elif [ -n "${TASK}" ];then
@@ -305,5 +312,4 @@ while (true); do
     esac
   fi
 done
-
 exit 0
