Update lite-software

diff --git a/32/usr/bin/lite-software b/32/usr/bin/lite-software
--- a/32/usr/bin/lite-software
+++ b/32/usr/bin/lite-software
@@ -31,29 +31,29 @@ log(){
 TMP_LOG=/tmp/lite-software.log
 
 prepare(){
-	# Check internet access
-	if eval "sudo -u ${SUDO_USER:-$USER} curl -sk https://www.linuxliteos.com/" >> /dev/null 2>&1; then
-	: # pass
-	else # Prompt ERROR internet connection
-		(zenity --info --ok-label="Got it!" --title="No Internet connection detected..." \
-			     --text="\n<b>Your computer does not seem to be connected to the internet</b> \n \nYou won't be able to install applications packages needed to be downloaded from the Internet." --no-wrap)
-		return 
-	fi
-   # Check if apt-cache was built and ask to update    	    	
- 	if zenity --question --width=400 --height=120 --title="     Update software sources" --window-icon=$ic --text="\n<b>Would you like to update your software sources now?</b>\n\nClick 'No' to continue without updating software sources or 'Yes' to update software sources next. \n \nIt is recommended to always update software sources before installing applications."; then
-		TOTALREPOS=$(cat /etc/apt/sources.list | grep '^deb' -c) # Total of repositories registered, this is approximated
-    		sudo apt-get update 2>&1 | awk -v total=$TOTALREPOS '/^Ign|^ Get/{count++;$1=""} FNR { if (total != 0){percentage=int (100*count/total);print (percentage < 90?percentage:90),"\n#",$0 }; fflush(stdout)}' \
-       		| zenity --progress --text="Updating package lists..." --window-icon=$ic --title="Updating Software Sources - please wait..." --percentage=0 --auto-close --width=600
-    		if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-      			zenity --error --title="          Error" --width=300 --height=90 --text="\n<b>Updating sources has failed</b>\n\nRefer to /var/log/lite-software.log for more information."
-      			log "ERROR: Updating sources has failed."
-      			next
-    		fi
-    		log "INFO: Software sources were updated."
-  	else
-    		log "INFO: The updating of packages was cancelled by the user"
-    	next
-  	fi
+  # Check internet access
+  if eval "sudo -u ${SUDO_USER:-$USER} curl -sk https://www.linuxliteos.com/" >> /dev/null 2>&1; then
+    : # pass
+  else # Prompt ERROR internet connection
+    (zenity --info --ok-label="Got it!" --title="No Internet connection detected..." \
+           --text="\n<b>Your computer does not seem to be connected to the internet</b> \n \nYou won't be able to install applications packages needed to be downloaded from the Internet." --no-wrap)
+    return 
+  fi
+   # Check if apt-cache was built and ask to update           
+  if zenity --question --width=400 --height=120 --title="     Update software sources" --window-icon=$ic --text="\n<b>Would you like to update your software sources now?</b>\n\nClick 'No' to continue without updating software sources or 'Yes' to update software sources next. \n \nIt is recommended to always update software sources before installing applications."; then
+      TOTALREPOS=$(cat /etc/apt/sources.list | grep '^deb' -c) # Total of repositories registered, this is approximated
+      sudo apt-get update 2>&1 | awk -v total=$TOTALREPOS '/^Ign|^ Get/{count++;$1=""} FNR { if (total != 0){percentage=int (100*count/total);print (percentage < 90?percentage:90),"\n#",$0 }; fflush(stdout)}' \
+      | zenity --progress --text="Updating package lists..." --window-icon=$ic --title="Updating Software Sources - please wait..." --percentage=0 --auto-close --width=600
+      if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+        zenity --error --title="          Error" --width=300 --height=90 --text="\n<b>Updating sources has failed</b>\n\nRefer to /var/log/lite-software.log for more information."
+        log "ERROR: Updating sources has failed."
+        next
+      fi
+        log "INFO: Software sources were updated."
+      else
+        log "INFO: The updating of packages was cancelled by the user"
+        next
+  fi
 }
 
 # Set app icon variable
