updated disabled auto login

diff --git a/usr/scripts/autologin-d b/usr/scripts/autologin-d
--- a/usr/scripts/autologin-d
+++ b/usr/scripts/autologin-d
@@ -1,48 +1,36 @@
 #!/bin/bash
 #--------------------------------------------
 # Description: Linux Lite Auto Login Dialogue
-# Author: Jerry Bezencon 2014
+# Authors: Jerry Bezencon, Ralphy
 # Website: https://www.linuxliteos.com
 #--------------------------------------------
 
+# variables
+APPNAME="Disable Auto Login"
+ic="/usr/share/icons/zenity-llcc.png"
+
+while (true); do
 # Main window dialogue.
- CONFIGURE_TITLE="Disable Auto Login
------------------------------------------------------------------------------------------------------
-This will Disable Auto Login.
-Next time you restart your computer, you will log in normally.
+zenity --question --icon-name="info" --window-icon="$ic" --ok-label="$APPNAME" --cancel-label="Quit" --width="440" --height="60" --title="$APPNAME" \
+       --text="\n                       <b>You are about to $APPNAME</b>\n \
 
------------------------------------------------------------------------------------------------------
-Click on Yes to continue or No to cancel."
+From next restart on, you will be prompted for your password to login.\n\n\
+Make sure you remember your account password before restarting the computer."
 
-# Call the zenity window icon location.
- INSTALL_ICON="/usr/share/icons/zenity-llcc.png"
- CONFIGURE="Disable Auto Login"
-        
-        zenity --question --title="$CONFIGURE" --window-icon="${INSTALL_ICON}" --text="${CONFIGURE_TITLE}"
+if [ "$?" -eq "0" ]; then
+    gksu -m '
+      <b>Your password is required to Disable Auto Login</b> 
 
-                if [ "$?" -eq "0" ]; then
-                        gksudo -g --message 'To proceed with this setting your password is required. Enter your password, or press Cancel.' "sed -i "s/autologin-user=$USER/autologin-user=linux/g" /etc/lightdm/lightdm.conf" | zenity --progress --title="$CONFIGURE" --window-icon="${INSTALL_ICON}" --text="Please wait whilst we enable $CONFIGURE..." --pulsate --width=400 --auto-close --auto-kill
-
-
-                                if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                        
-                                        zenity --error \
-                                        --title="Error" --text="$CONFIGURE has not been applied."
-                                        exit 0
-                                fi
-
-                else
-
-                                        exit 0
-                fi
-
-
-PROCEED=$(zenity --info --title="$CONFIGURE" --window-icon=/usr/share/icons/zenity-llcc.png --text="Auto Login has been Disabled."; echo $?)
-if [ ${PROCEED} -eq 1 ]; then
-	zenity --info --title="Finished" --window-icon="${INSTALL_ICON}" --text="Auto Login Disabled."
-	exit;
+Please enter your password to continue, or press Cancel to exit now.' "sed -i "s/autologin-user=$USER/autologin-user=linux/g" /etc/lightdm/lightdm.conf"
+        if [ "${PIPESTATUS[0]}" -eq "0" ]; then
+                zenity --info --width="200" --height=40 --title="   $APPNAME" --window-icon=$ic --text="\nAuto Login has been Disabled!"
+                exit 0
+        else
+                zenity --error --width="200" --height="40" --title="$APPNAME - Error" --text="\nAuto Login could not be disabled."
+                continue
+        fi
 else
-	exit
+        exit 0
 fi
-
+done
 exit 0
