cleanup and optimization
Cleanup zenity dialogs output
Replace Install Updates plain text dialog with HTML
code cleaned up and reorganize execution

diff --git a/usr/scripts/updates-gui b/usr/scripts/updates-gui
--- a/usr/scripts/updates-gui
+++ b/usr/scripts/updates-gui
@@ -6,124 +6,136 @@
 # Website: https://www.linuxliteos.com
 #-----------------------------------------------------------------------------------------
 
-# Kill off any package managers that may be running
-if [ "$(pidof synaptic)" ]
-then
-   killall -9 synaptic
-fi
+_APPNAME="Linux Lite Updates"                # Application name variable
+_MYUPDUSER=$(whoami)
+_ICON="/usr/share/icons/Faenza/apps/scalable/synaptic.svg"     # Linux Lite icon variable
+_UPDATES=$(mktemp /tmp/updateslist.XXXXXX)   # Updates log variable
+_DATE=$(date +"%A-%d-%B-%Y-%T")              # Date variable
+_TMPU="/tmp/_updusr"
+_PLAIN="/tmp/updateslist.txt"
+if [ ! -f "$_TMPU" ]; then echo "$_MYUPDUSER" > "$_TMPU"; fi
+_SVUSER=$(cat "$_TMPU")
 
-if [ ! -z "$(pgrep gdebi-gtk)" ]
-then
-   killall -9 gdebi-gtk
-fi
+# function remove temp files
+rm_temp_files() {
+rm -f $_SVUSER
+rm -f $_TMPU
+rm -f $_UPDATES
+rm -f $_PLAIN
+rm -f /tmp/updateslist.*
+}
 
 # Check Internet access
-if eval "curl -sk google.com" >> /dev/null 2>&1; then
-  :  # continue - internet connection check passed
-else # Prompt ERROR internet connection check failed and exit
-    zenity --info --width=400 --height=120 --ok-label="Close" --title="  Lite Updates - No Internet connection detected" \
-           --text="\n<b>Your computer does not seem to be connected to the internet</b> \n \nLinux Lite cannot check for updates. Please check your Internet connection and try again."
-    exit 0
+if eval "curl -sk google.com" >> /dev/null 2>&1; then :; else # Prompt ERROR internet connection check failed and exit
+  zenity --info --width="320" --height="120" --ok-label="Close" --title="  $_APPNAME" \
+         --text="\n<b>Your computer is not connected to the internet</b> \n \nLinux Lite cannot check for updates. Please check your internet connection and try again." 2>/dev/null
+  rm_temp_files; exit 0
 fi
 
-APPNAME="Linux Lite Updates"                # Application name variable
-ic="/usr/share/icons/zenity-llcc.png"       # Linux Lite icon variable
-UPDATES=$(mktemp /tmp/updateslist.XXXXXX)   # Updates log variable
-DATE=$(date +"%A-%d-%B-%Y-%T")              # Date variable
+# Kill off any package managers that may be running
+if [ "$(pidof synaptic)" ]; then killall -9 synaptic; fi
+if [ ! -z "$(pgrep gdebi-gtk)" ]; then killall -9 gdebi-gtk; fi
 
 # start dialog - Ask for elevation, else exit
 if [ $EUID -ne 0 ]; then
-   zenity --question --width=320 --height=100 --window-icon=$ic --ok-label="Continue" --cancel-label="Cancel" --title="  $APPNAME" \
-       --text="\nLinux Lite will now fetch the Updates list\n\nClick <b>Cancel</b> to exit now or <b>Continue</b> to proceed."
+   zenity --question --width="320" --height="100" --window-icon="$_ICON" --ok-label="Continue" --cancel-label="Cancel" --title="  $_APPNAME" \
+       --text="\nLinux Lite will now fetch the Updates list\n\nClick <b>Cancel</b> to exit now or <b>Continue</b> to proceed." 2>/dev/null
    case $? in
-      0) pkexec $0
-         exit
-         ;;
-      1) exit
+      0) pkexec "$0"; if [ "${PIPESTATUS[@]}" -eq "126" ]; then rm_temp_files; fi; exit 0 ;;
+      1) rm_temp_files; exit 0 ;;
    esac
 fi
 
 if [ "$?" -eq "0" ];then
   APTUPDATE=$(grep '^deb' -c /etc/apt/sources.list) # Total of repositories registered, this is approximated
   apt-get update 2>&1 | awk -v total=$APTUPDATE '/^Ign|^ Get/{count++;$1=""} FNR { if (total != 0){percentage=int (1000*count/total);print (percentage < 90?percentage:99),"\n#",substr($0, 0, 128) }; fflush(stdout)}' \
-    | zenity --progress --text="Updating package lists..." --window-icon=$ic --title="Updating Software Sources - please wait..." --percentage=0 --no-cancel --pulsate --auto-close --width=600
+    | zenity --progress --width="600" --text="Updating package lists..." --window-icon="$_ICON" --title="Updating Software Sources - please wait..." --percentage="0" --no-cancel --pulsate --auto-close 2>/dev/null
       if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-          unset APTUPDATE
-          rm $UPDATES
-          unset UPDATES
-          zenity --error --width=290 --height=60 --title="  $APPNAME - Error" \
-                 --text="\n$APPNAME couldn't fetch the package cache information lists.\n\nCannot check for updates!"
+          unset APTUPDATE; rm_temp_files; unset _UPDATES
+          zenity --error --width="290" --height="60" --title="  $_APPNAME - Error" \
+                 --text="\n$_APPNAME couldn't fetch the package cache information lists.\n\nCannot check for updates!" 2>/dev/null
           exit 1
       fi
   unset APTUPDATE
 
-# Creates a list in /tmp/updateslist
-  apt-get --just-print dist-upgrade 2>&1 | perl -ne 'if (/Inst\s([\w,\-,\d,\.,~,:,\+]+)\s\[([\w,\-,\d,\.,~,:,\+]+)\]\s\(([\w,\-,\d,\.,~,:,\+]+)\)? /i) {print "Name: $1 INSTALLED: $2 AVAILABLE: $3\n"}' | awk '{print NR,":\t"$0}' | tee $UPDATES
+  # Creates a list in /tmp/updateslist
+  # initialize html page
+  ( echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Final//EN">'
+  echo '<html style="width: 98%;"><head>'
+  echo "<title>List of available Updates</title>"
+  echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">'
+  echo "<style>"
+  echo "    body    { background: #fff }"
+  echo "    .title  { font: bold 90% serif; color: #0066FF; padding: 10px 0 1px 0 } "
+  echo "    .stitle { font: bold 90% sans-serif; color: #0044DD; padding: 10px 0 10px 0 } "
+  echo "    .sstitle{ font: bold 80% serif; color: #000000; background: #efefef; } "
+  echo "    .field  { font: 70% sans-serif; color: #000000; padding: 2px; padding-left: 5px } "
+  echo "    .value  { font: 60% sans-serif; color: #505050 } "
+  echo "    hr.x { color:#FFFFFF; background-color:#FFFFFF; border:1px double black; dotted #888888; border-style:none none dotted; } "
+  echo "</style> "
+  echo '</head><body style="width: 100%;">') >> $_UPDATES
+  echo '<p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAG7AAABuwBHnU4NQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAxCSURBVGiB1ZpdjCTXVcd/59ZXz/R0z8yOvev1x+7aGIKDHdlBVkBYiEhEigIoQkLiBYgt3lGCkBDIT0G8IYR4QLwEJB6SByMhFBRFygvCYSFxsBIgXn/E69j7NTvrnd2Znv6quvccHm5VdfdMz669ih+40t1bc+tW9fmf//m6t1bMjP/PzX3E75e6f2QtXfg1kQToAPlnfumZlU//8tMbZ07f319b666vFiv9LGc9S1zP4XoO6yWOnpn2RHTN1NYEv4ZJv/vAxx6XJEnKyVi66ycoJ0Mz9f7mm+ffUrN9we0ZMlDTgZrbR2Q/qA18cANvYTCd2mA4Dvv7o8Fge3t/8O1XXx+8/F8XJkAJTMwsHAEgIsVvf+65s3/6pS/84/r6iSdFREwDGiosBIJ6LHg0eFQ9pp4QQpzTgKnHNBDMcFkOQLROh0syIckyDdXH0yRBHDgn4HKcSxBxcUySOLrF8Xd/69NUVTnd3nn/m3/+t//0JRG5ambTFkCt+c0/+eLz31zvrz9ajW4TfImZYhowVcwCqtpem8Z7atpemypB/bF0+7LEFTkOUAQniplDBAwQi6CPjEBerBTnzp77/B8+/2sr//bdN74gIjfMLDQ+sAKcPrF137lqMkBDFZ80xcwiELNj5nQ2Rz13TDOJ7mD1v2aRpubd7YjF+804d//RMw//CnC6lrl14gzYEpeI+vKIgFY/vHzOFuaCHg9A9QMIiy0FRX2/s7KaA1u1zC2ABCjagPGBNH/MnIbDcs8jaAVpux3TD62bAYEoK8k8AAFERD6E5pfPqemx8hvhg5nMMSxYC2wWnt2hX7h3zdfXqscD0DAT4qiwM0KYU3aj83Y8ZKHzAJzBPWu+mdNwBx9ohFom7F2cd9EfZnIfysR2RKMfno07mNC9mM2hdTMujgKQBoCZ1i/U9iWLYfN4NvQOeQDzMyE+oPMevl+H6bY8mXdiZ0s0+kHnGjZUDSzETphdW4gm9BNhAdeAWKiFmBNumZaPsMExbIQyvi9UmFazv+vnpRZG6mcXR+r7UULjaGaeb/MA3L1ovp2rganOAFgo2w6zNDAvjBiLwtYZeim4Gvy86S8yMEfh3Wz+uDlVw7QGoDUDWmd3wiIDd2LiDuuWMeBmDNy7H7Sh1E8RkSi41iwcckT5kM47WzeTd4EKQG5cv45L83vSfDMXahOKvap7ifppjLBzAt/VeY+sg6tXrsNcFJo3IammB2ycPIWGgK9GIA7nBJO0dn6rDc1mypj/ITO8G5KvruOcA5eTr/RJ0gwNStE7QbG2CggiIAiIIOJAJD4jDnHxbwTMpPYTIUkyQsz0SwGQ2BgD3MoG3f5JJpMJ08mkHcfjCZPJmPF4zGQc58fjen46ZTKeMBgM+f3fgSSJ5A533gbAB+Wlr/87a6srdIqMvJNT5BlFnlMUBZ0ipSiKeN3JWekUFJ0Oqysr9Db6BEvIuj1Gt/97qQ8AuGo8iFRYxZU3v085GVFVAR8CofIEHwiqiA/kQUkIdLJAT5RQCH41Y9BZwaU5LllM8o7Aoye79Lsd0jTFJQlp6khSI0k8SWKkKEk1AUspfYqNE6qDlPFgh1NnPw7A4Ob7C6a/wEA1nWCq3N5+BwsVeZaT59LWfSKCSEN7HDFBXB0Sgb39IUmatQw0zcTxzLNPs7G+FpVU27bpMXUP1lYNFgK3tt/h5NknmU6GSxkQwPlqivcl5XSCmRGCZ+fqNtW0TkS14CKOEw+cor+xCSI02d0w1ASXZrgkOcSAB5sdUsy5VB0AiGG4jlCxLLfW/qvpBO9LqumkYeBIJhZTxZdTQjnFVNm5fI3eiQ26az1wgpOkdba3f/haBIC0WUgQBEOSDJcuAhATtJZYiKCtCQpWv6BJbKr1n02AEEJV4suy8d4jtRAAqko1mRB8iapSTiesdFe58s6PqcoSNePyxYtUVUWaZYfqwplmkzQjSfOF7pKsFabdlzURVSILWifC2OMhQbxWvPdUk/GRU6Z5ExJTpSonMcYjmBnlZMLlty9SVSUPPfoYl958C19WJEna0i8mmER9BqNmYDHJO7WYMtrCIf6r9Tswq/NEhNfuvtocA1U5iaF2bke2YEKqSgih3lU5zIyqrBDnCD7gm+sQcEmCqtXObNEMmuMR5xB3yIRcQpPHavvBDEIwQq1tR33CoYparGqjr1i9NsTfW5IHpAGgGtptoZmRdzq4JGG11yNf6ZCkKd1+n+l4jLWbl8gWIvW5EUebgWmMOiEo482AO1Ug/RTXX0GAas+jewF/ZUC6XeFqVhsAqn4ewBEGnKmi3kcnqgHMrnVWixgLYwx5tUEE5ZXvvEpZllTTkrIsCWVF0MDPPP4IIysJn8jRUyWjcJ1Sh0ynBwAU3TXyXpfibA9/dZXwnzfJ28oU1HvELe7lFwxVVdGwyIC2NTA1rdHZrHY45xqNx5Tf6eSshTFJUZBsrJImjiRJEBFGG8r0k8IBl7i5d5GyGrWRqDU1hDxbZevEY3Q/e5KD87dYvRkAQUOI5cdcWwBgqmiYMRAdq7FXxUJtk9oUcAENzdFgfHEnz+jk2REL2q9KJk9V3Crf5Pb0Et4HThZPHFkHsDO6wLD8ARvFI2w+e4bhN/ZYJUWDR46JQtA6sW8ZSLKM0fCAJ37+GRCHqvLUL/4CIo7LP/oRqtoWZVan4mVn6VUVGDwx5WZ1kVuTSwAEDxvdc0sBXDl4DTXPTvUOVcez/swjJN8ZEYKHuznxLAoZ/c0N9nZvsXdzFxHXlg9OEjZPnYoA6qelzmaH/dfMuJEN2d+4ye7wSjRDwJfKieKnlgLwZaAx893hFdL7u5S9jL5vGTjeieMRetwFiQib921F4Z3D1eHRJSniBPMeXMzqtqCXOWGCstff5/2D9yjD7NixKuH+leUAqpI5Nw3cOHiP/vpD+P2qlfUwAwCiZgRfoaYzWdQQqfei1qR+i7FeBFEXY397Rr4oTFl6JmtjhtMhzPFTlcbJtceOAWBIOlvr/ZDueqC8Ud7RhKB14hAdt05Srt6BBzGcKUHcgkk1G5O2JJ1ro+GEcWeA901giDB8ZZxe/+mlAHxlSGXMRDUm3RHj8WS+9lmWiW3OiYXdWwNG45LKR2ctipwzD96H0eyeiDsoGtkOBzkYT6cMJyN8GvH1qnN88Vf/jszlpEm+FMCfffY8lZb81bdeYJC/iwgc+AMm05KM4xlwqkrwHg0KIqwUGUWWkqYJJpCKYzQax6gjjrxIcSKLgh9CICjVjuJPRpPYGb/NS//6N/zB5/9iqfAA9/Ue5q//+Y/YmVwkr/cV1fWAk6YMPOZgy+xoHlD1TKfRJzR1aKhPIETIkhW0duAWxOE4bQo7gj8RAbhCOH/tazz+yif43LO/txTAN175B85f+xrdrQTva7+7LmSOtiRv2sKpRMuAKk1dVAUFFOeU6XRK0PgNIM8Sgvf44OMzviL4ilAtdrGA23Z4T9vzfsJXXn6RC5e+d0T4C5e+x1defpG8nyw8k2w7pK6S59W0eLir1jJgqngfCKVnWpaMp56q9KCBEJTJeBILP+9j+VF3O9RFlQemXdxbGcEbwRsajM6W8eWvvsDuwfVWgN2D63z5qy/Q2YprmvXurYxTZRcsxPOkYwDotd3hXvBVy0CRJfS6Bb2VgrVORn+tQ1FkrHYyOkVGCDHxheCP7aqe9dWE+9/oYQeC94b38Vua39zlxb9/Hh8qfKji9eZuvFevswPhvjd6bHQzNHi2b432iduIaKL1OAX2zr+2/fpvPvf4p6yufe7WGmtcZvvzzSXw0HqX98+POPjUBO3U73bCZfsBf/nSHwNw2X5A7hy+zndu7Fj9boeH+13SxGEI/3Fh+wKwV8uMmBki0gOeylP3G5/55Nlff+7JB8+e3lrrxUMmaWN+G/udOzInzaGULK6HOjiocmsw4q1rO1x6+Brjh2anC5PbUeLOxmwTVLxXcPqdTR7d2mB9JWV7dzj49v9effdbr777L6XXrwP/Y2aDBoAAp4CfA54GzgHrd6Xg3loK9O//2eLM1sfyExtnstXeg1kXYHC1Gt5+rxrdfKPcvfH69D1gH2i+mOwBPwa+D/wQuG5mJs1pr0R1bQIP1MIvzzI/mZYAa8SP1etAv57frwUdAwfA/Dfbsr63Ddyy2sZbAE0TkZSopY/6f7I0zVF/8yUKfJzzKeDNbOEb1v8BmSBqeHp22RIAAAAASUVORK5CYII=" alt="" width="32" height="32" style="float:left; margin:0 5px 5px 0;" /></p>' >> $_UPDATES
+  echo '<h1 class="title">Updates Available for your System</h1><table style="width: 100%;">' >> $_UPDATES
+  ( echo "<tr><td class="value"><i>Click <b>Update Now</b> to install the updates listed below or <b>Cancel</b> to exit.</i></td></tr>" && echo '<tr><td><hr class="x"/></td></tr>') >> $_UPDATES
+  ( echo "<tr><td colspan="2" class="sstitle">List of available Updates</td></tr>" && echo "<tr><td><p></p></td></tr>") >> $_UPDATES
 
-# Check if updates are available, if there are none, remove /tmp/updateslist.XXXXXX and pop up a 'your system is up-to-date. Available' dialog
-  if [  -z "$(cat $UPDATES)"  ]; then
-    rm $UPDATES
-    unset UPDATES
-    zenity --info --window-icon=$ic  --width=180 --height=60 --title="  $APPNAME" \
-           --text="\nYour system is up to date."
-    exit 0
-  fi
+  apt-get --just-print dist-upgrade 2>&1 | perl -ne 'if (/Inst\s([\w,\-,\d,\.,~,:,\+]+)\s\[([\w,\-,\d,\.,~,:,\+]+)\]\s\(([\w,\-,\d,\.,~,:,\+]+)\)? /i) {print "Name: $1 INSTALLED: $2 AVAILABLE: $3\n"}' | awk '{print NR,":\t"$0}' > $_PLAIN
+  sed '
+  s:^:<tr><td class="field">:;
+  s:$:</td></tr>:
+  ' $_PLAIN >> $_UPDATES
+  # updates footer
+  ( echo "<tr><td><p></p></td></tr>" && echo "</html>" ) >> $_UPDATES
 
-# Insert text into  /tmp/updateslist.XXXXXX
-  sed -i -e '1 i\       List of available Updates' -e '1 i\       -----------------------------------' -e '1 i\       Click "Update Now" to install the updates listed below or "Cancel" to exit now\n'  $UPDATES
+  # Check for available updates; if none then remove /tmp/updateslist.XXXXXX and display up-to-date dialog
+      if [  -z "$(cat $_PLAIN)"  ]; then
+        rm_temp_files; unset _UPDATES
+        zenity --info --window-icon="$_ICON"  --width="180" --height="60" --title="  $_APPNAME" \
+               --text="\nYour system is up to date." 2>/dev/null
+        exit 0
+      fi
 
 # Erase existing available info
-  dpkg --clear-avail
-  else
-    rm $UPDATES
-    unset UPDATES
-    exit 0
-  fi
+dpkg --clear-avail
+else
+  rm_temp_files; unset _UPDATES; exit 0
+fi
 
 # Call the zenity dialog to show update list
-zenity --text-info --ok-label="Update Now" --cancel-label="Cancel" --title="  $APPNAME" --width=750 --height=340 --filename="$UPDATES"
+zenity --text-info --window-icon="$_ICON" --ok-label="Update Now" --cancel-label="Cancel" --title="  $_APPNAME" --width="750" --height="400" --html --no-interaction --filename="$_UPDATES" 2>/dev/null
       if [ "$?" -eq "0" ];then
-        # Continue script if no halt and Remove tmp file and unset variables
-        rm $UPDATES
-        unset UPDATES
+        # Continue script if no halt, remove tmp file and unset variables
+        rm $_UPDATES; unset _UPDATES
 
 #Begin upgrade
 DEBIAN_FRONTEND=noninteractive apt-get  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade -y  2>&1 | tee /var/log/llupdates.log | awk ' BEGIN { FS=" "; total=1;end_download=0} /upgraded/ {total= $1 + $3;FS="[ :]" } /^Get:[[:digit:]]+/ {printf "#Downloading %s %s %s\n",$7,$(NF-1),$NF;print int(($2 - 1) * 100 / total); fflush(stdout)} /^\(Reading / {if (end_download==0){print 100;fflush(stdout);end_download=1}} /^(Preparing|Unpacking|Selecting|Processing|Setting|Download)/ {print "#", substr($0, 0, 128); fflush(stdout)}' \
-    | ( zenity --window-icon=$ic --progress --width=600 --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage=0 --no-cancel --auto-close ; zenity --progress --window-icon=$ic --width=600 --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..." --no-cancel --pulsate --auto-close )
+    | ( zenity --progress --width="600" --window-icon="$_ICON" --text="Downloading package(s)...\nThis may take a while." --title="Downloading - please wait..." --percentage="0" --no-cancel --auto-close 2>/dev/null ; zenity --progress --window-icon="$_ICON" --width="600" --text="Installing and configuring packages...\nThis may take a while." --title="Installing - please wait..." --no-cancel --pulsate --auto-close )
 
-      if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-         zenity --error --width=240 --height=60 --title="  $APPNAME - Error" \
-                --text="$APPNAME have failed. For more information refer to: \n \n/var/log/llupdates.log"
-         exit 0
-      fi
-      # Halt updates script if user selects Cancel
-      else
-         rm $UPDATES
-         unset UPDATES
-         zenity --info --width=200 --timeout=3 --window-icon="$ic" --title="  $APPNAME" --text="\nUpdates have been canceled."
-         exit 0
+    if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+       zenity --error --width="240" --height="60" --title="  $_APPNAME - Error" \
+              --text="$_APPNAME have failed. For more information refer to: \n \n/var/log/llupdates.log" 2>/dev/null
+       rm_temp_files; exit 1
+    fi
+    # Halt updates script if user selects Cancel
+    else
+       rm_temp_files; unset _UPDATES
+       zenity --info --width="200" --timeout="3" --window-icon="$_ICON" --title="  $_APPNAME" --text="\nUpdates have been canceled." 2>/dev/null
+       exit 0
     fi
 
-    PROCEED=$(zenity --question --width=300 --height=80 --title=" $APPNAME" --window-icon="$ic" --text="\n$APPNAME completed successfully!\n\nWould you like to view the $APPNAME log?"; echo $?)
-    if [ ${PROCEED} -eq 1 ]; then
-        continue
-    else
-      zenity --text-info --cancel-label="Quit" --ok-label="Save"  --title=" $APPNAME - Log" --width=650 --height=340 --filename="/var/log/llupdates.log"
-          if [ $? -eq 0 ]; then
-            # Save report
-            szSavePath=$(zenity --title="    Save log" --width=550 --height=380 --file-selection --filename=llupdates-"${DATE}".txt --file-filter='*.txt' --file-filter='All files | *' --save --confirm-overwrite)
-            sudo -u ${SUDO_USER:-$USER} cp /var/log/llupdates.log $szSavePath
-          else
-          continue
-          fi
+    PROCEED=$(zenity --question --width="300" --height="80" --title="  $_APPNAME" --window-icon="$_ICON" --text="\n$_APPNAME completed successfully!\n\nWould you like to view the $_APPNAME log?" 2>/dev/null ; echo $?)
+    if [ ${PROCEED} -eq 1 ]; then rm_temp_files; :; else
+      zenity --text-info --cancel-label="Quit" --ok-label="Save"  --title="  $_APPNAME - Log" --width="650" --height="340" --filename="/var/log/llupdates.log" 2>/dev/null
+        if [ $? -eq 0 ]; then
+          # Save report
+          szSavePath=$(zenity --width="550" --height="380" --title=" Save Updates log" --file-selection --filename=/home/$_SVUSER/llupdates-"${_DATE}".txt --file-filter='*.txt' \
+                              --file-filter='All files | *' --save --confirm-overwrite 2>/dev/null)
+          sudo -u ${SUDO_USER:-$_SVUSER} cp /var/log/llupdates.log $szSavePath; rm_temp_files; else rm_temp_files; :
+        fi
     fi
     if [ -s /var/run/reboot-required ]; then
-        zenity --question --ok-label="Reboot now !" --cancel-label="Continue using my system" --title=" $APPNAME - Reboot required" --width=300 --height=100 \
-               --text="\nPrevious updates require rebooting the system for changes to take effect.\n\n          Would you like to reboot now?"
-            if [ "$?" -eq "0" ]; then
-                reboot
-            else
-              exit
-            fi
+        zenity --question --width="300" --height="100" --ok-label="Reboot now !" --cancel-label="Continue using my system" --title=" $_APPNAME - Reboot required" \
+               --text="\nPrevious updates require rebooting the system for changes to take effect.\n\n          Would you like to reboot now?" 2>/dev/null
+        if [ "$?" -eq "0" ]; then reboot; else exit 0 ; fi
     fi
 exit 0
